[project]
name = "PiePie"
version = "0.1.0"
description = "**PiePie** is a networked personal finance app unifying expense tracking and shared ledgers. Built on Django and React, its 'Unified Entity Model' treats accounts, contacts, and friends as entities within a chat-centric interface, seamlessly managing solo and social transactions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
