# Generated by Django 6.0 on 2025-12-12 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits, dots and dashes only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots, and dashes.', regex='^[a-zA-Z0-9.-]+$')]),
        ),
    ]
